### ISSUE TITLE
CLI segfault during ziti edge create ca

### ISSUE THREAD

**Issue by qrkourier** [openziti/ziti#1150]
```bash
❯ ziti edge create ca "kentest Cyan CA" ~/.config/ziti/environments/pki/cyan/certs/cyan.cert --auth --autoca --output-json 
{"data":{"_links":{"self":{"href":"./cas/5lkf2KumXfrGaqpgoiICE2"}},"id":"5lkf2KumXfrGaqpgoiICE2"},"meta":{}}

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x2b8527a]

goroutine 1 [running]:
github.com/openziti/ziti/ziti/cmd/edge.runCreateCa(0xc000b9d8c0)
        github.com/openziti/ziti/ziti/cmd/edge/create_ca.go:146 +0x39a
github.com/openziti/ziti/ziti/cmd/edge.newCreateCaCmd.func2(0xc000bedb00?, {0xc000112370?, 0x5?, 0x5?})
        github.com/openziti/ziti/ziti/cmd/edge/create_ca.go:90 +0x70
github.com/spf13/cobra.(*Command).execute(0xc000bedb00, {0xc000112320, 0x5, 0x5})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x505ff60)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/openziti/ziti/ziti/cmd.Execute()
        github.com/openziti/ziti/ziti/cmd/cmd.go:81 +0x38
main.main()
        github.com/openziti/ziti/ziti/main.go:51 +0x17

❯ ziti version
NAME             VERSION
ziti             v0.28.0
ziti-controller  v0.0.0
ziti-prox-c      not installed
ziti-router      v0.0.0
ziti-tunnel      v0.0.0
ziti-edge-tunnel v0.21.5-local

❯ curl -ksSf https://client.canary.openziti.io:443/edge/client/v1 | jq .data.version
"v0.28.0"

```

**Comment by qrkourier** [comment]
How I created the CA cert:

```bash
❯ ziti pki create ca --ca-name cyan --ca-file cyan --pki-root ~/.config/ziti/environments/pki
Success
```

**Comment by qrkourier** [comment]
```bash
❯ ziti edge list cas
╭────────────────────────┬────────────────────┬────────┬───────────┬─────────────┬───────────────────────────────────────────────────────────────╮
│ ID                     │ NAME               │ FLAGS  │ TOKEN     │ FINGERPRINT │ CONFIGURATION                                                 │
├────────────────────────┼────────────────────┼────────┼───────────┼─────────────┼───────────────┬──────────────────────┬────────────────────────┤
│ 1Mh6VPNScwB6Adk8aKsS6N │ kentest magenta CA │ [VAE]  │ -         │ 1a85...a6   │ AutoCA        │ Identity Name Format │ [caName]-[commonName]  │
│                        │                    │        │           │             │               ├──────────────────────┼────────────────────────┤
│                        │                    │        │           │             │               │ Identity Roles       │                        │
├────────────────────────┼────────────────────┼────────┼───────────┼─────────────┤               ├──────────────────────┼────────────────────────┤
│ 5lkf2KumXfrGaqpgoiICE2 │ kentest Cyan CA    │ [AE]   │ SmQXlzqLx │ -           │               │ Identity Name Format │ [caName]-[commonName]  │
│                        │                    │        │           │             │               ├──────────────────────┼────────────────────────┤
│                        │                    │        │           │             │               │ Identity Roles       │                        │
╰────────────────────────┴────────────────────┴────────┴───────────┴─────────────┴───────────────┴──────────────────────┴────────────────────────╯
results: 1-2 of 2

Flags: (V) Verified, (A) AutoCa Enrollment, (O) OttCA Enrollment, (E) Authentication Enabled
```

**Comment by smilindave26** [comment]
Cannot reproduce
