### ISSUE TITLE
ziti cli identity tags related flags misbehaving

### ISSUE THREAD

**Issue by sabedevops** [openziti/ziti#1204]
ziti version: `0.28.4`

Description:
------------------

The following succeeds, however, the tags are never actually added to the identity. 

cmd: `ziti edge create identity user dummy --tags-json '{"foo": "bar"}'`

result: `"tags": {},"`

---
The following fails, but should succeed.

cmd: `ziti edge create identity user dummy --tags foo=bar`

result:
```go
panic: invalid tags JSON: unexpected end of JSON input

goroutine 1 [running]:
github.com/openziti/ziti/ziti/cmd/api.(*EntityOptions).GetTags(0xc0009518c0)
        github.com/openziti/ziti/ziti/cmd/api/options.go:94 +0x1b3
github.com/openziti/ziti/ziti/cmd/api.(*EntityOptions).SetTags(0x3541cb4?, 0x2fec520?)
        github.com/openziti/ziti/ziti/cmd/api/options.go:108 +0x1e
github.com/openziti/ziti/ziti/cmd/edge.runCreateIdentity({0x3533e67, 0x4}, 0xc0009518c0)
        github.com/openziti/ziti/ziti/cmd/edge/create_identity.go:176 +0xc67
github.com/openziti/ziti/ziti/cmd/edge.newCreateIdentityOfTypeCmd.func1(0xc0009d2600?, {0xc000a55b90?, 0x3?, 0x3?})
        github.com/openziti/ziti/ziti/cmd/edge/create_identity.go:79 +0x7a
github.com/spf13/cobra.(*Command).execute(0xc0009d2600, {0xc000a55b30, 0x3, 0x3})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0x5072f60)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
github.com/openziti/ziti/ziti/cmd.Execute()
        github.com/openziti/ziti/ziti/cmd/cmd.go:81 +0x38
main.main()
        github.com/openziti/ziti/ziti/main.go:51 +0x17
```

---
The following succeeds, but should fail due to nested dictionary.

cmd: `ziti edge create identity user dummy --tags-json '{"foo": {"bar": "baz"}}'`
result: success with `"tags": {},`

**Comment by chrda81** [comment]
Hi,

I wanted to set the "fullname" tag when creating an identity and ran into the same problems. When is the fix expected to be released?

**Comment by plorenz** [comment]
> Hi,
> 
> I wanted to set the "fullname" tag when creating an identity and ran into the same problems. When is the fix expected to be released?

I'll see if I can sort this out today. There's no fix yet, there's a referenced PR, but it's from before when we merged the projects and it's unrelated.
