### ISSUE TITLE
PUT on Identity using authPolicyId:null causes panic

### ISSUE THREAD

**Issue by rentallect** [openziti/ziti#1612]
I wanted to "detach" an AuthPolicy from an Identity, so I did a PUT on the Identity using `"authPolicyId": null` in the body.  The thread handling the request in the controller panic'ed like this:

```
[176601.020]   ERROR fabric/controller/api.(*timeoutHandler).ServeHTTP.func1.1: panic caught by timeout next: runtime error: invalid memory address or nil pointer dereference
goroutine 1258505 [running]:
github.com/openziti/foundation/util/debugz.generateStack(0x2000, 0x0)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/foundation@v0.17.25/util/debugz/stack.go:39 +0x58
github.com/openziti/foundation/util/debugz.GenerateLocalStack()
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/foundation@v0.17.25/util/debugz/stack.go:34 +0x2c
github.com/openziti/fabric/controller/api.(*timeoutHandler).ServeHTTP.func1.1()
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/fabric@v0.17.135/controller/api/timeouts.go:75 +0x4c
panic({0x102773b20, 0x1035faf60})
	/usr/local/go/src/runtime/panic.go:844 +0x26c
github.com/openziti/edge/controller/internal/routes.MapUpdateIdentityToModel({0x14000e7e823, 0x9}, 0x1400048ef50, {0x14000f38ed8, 0x4})
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/internal/routes/identity_api_model.go:174 +0x338
github.com/openziti/edge/controller/internal/routes.(*IdentityRouter).Update.func1({0x14000e7e823, 0x9})
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/internal/routes/identity_router.go:212 +0xa8
github.com/openziti/edge/controller/internal/routes.UpdateAllowEmptyBody(0x14001e03a40, 0x14002cf6d78)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/internal/routes/base_router.go:288 +0x238
github.com/openziti/edge/controller/internal/routes.Update(0x14001e03a40, 0x14002cf6d78)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/internal/routes/base_router.go:275 +0x28
github.com/openziti/edge/controller/internal/routes.(*IdentityRouter).Update(0x140004b8530, 0x1400164b200, 0x14001e03a40, {0x140031fab00, {0x14000e7e823, 0x9}, 0x1400048ef50})
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/internal/routes/identity_router.go:211 +0x98
github.com/openziti/edge/controller/internal/routes.(*IdentityRouter).Register.func4.1(0x1400164b200, 0x14001e03a40)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/internal/routes/identity_router.go:74 +0x5c
github.com/openziti/edge/controller/env.(*AppEnv).IsAllowed.func1({0x102a0c0e0, 0x140022e59e0}, {0x102a04808, 0x1029eb688})
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/env/appenv.go:601 +0x234
github.com/go-openapi/runtime/middleware.ResponderFunc.WriteResponse(0x140022e5ec0, {0x102a0c0e0, 0x140022e59e0}, {0x102a04808, 0x1029eb688})
	/Users/curt/Repos/nf/github/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:69 +0x4c
github.com/go-openapi/runtime/middleware.(*Context).Respond(0x140016e3650, {0x102a0c0e0, 0x140022e59e0}, 0x140031fad00, {0x14000fc5dd0, 0x1, 0x1}, 0x140031faa00, {0x10278b500, 0x140022e5ec0})
	/Users/curt/Repos/nf/github/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/context.go:510 +0x610
github.com/openziti/edge/rest_management_api_server/operations/identity.(*UpdateIdentity).ServeHTTP(0x14000d2d1a0, {0x102a0c0e0, 0x140022e59e0}, 0x140031fab00)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/rest_management_api_server/operations/identity/update_identity.go:93 +0x490
github.com/go-openapi/runtime/middleware.NewOperationExecutor.func1({0x102a0c0e0, 0x140022e59e0}, 0x140031fab00)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/operation.go:28 +0xa0
net/http.HandlerFunc.ServeHTTP(0x14001581ff0, {0x102a0c0e0, 0x140022e59e0}, 0x140031fab00)
	/usr/local/go/src/net/http/server.go:2084 +0x48
github.com/go-openapi/runtime/middleware.NewRouter.func1({0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/router.go:78 +0x9c
net/http.HandlerFunc.ServeHTTP(0x14002931b60, {0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/usr/local/go/src/net/http/server.go:2084 +0x48
github.com/go-openapi/runtime/middleware.Redoc.func1({0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/redoc.go:72 +0x158
net/http.HandlerFunc.ServeHTTP(0x14002a07840, {0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/usr/local/go/src/net/http/server.go:2084 +0x48
github.com/go-openapi/runtime/middleware.Spec.func1({0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/go-openapi/runtime@v0.24.1/middleware/spec.go:46 +0x158
net/http.HandlerFunc.ServeHTTP(0x14002a07880, {0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/usr/local/go/src/net/http/server.go:2084 +0x48
github.com/openziti/edge/controller/server.ManagementApiHandler.newHandler.func1({0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/edge@v0.21.216-0.20220520195707-9dc15587296c/controller/server/management-api.go:133 +0x214
net/http.HandlerFunc.ServeHTTP(0x14002931c60, {0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/usr/local/go/src/net/http/server.go:2084 +0x48
github.com/gorilla/handlers.(*cors).ServeHTTP(0x140029f7290, {0x102a0c0e0, 0x140022e59e0}, 0x140031fa800)
	/Users/curt/Repos/nf/github/pkg/mod/github.com/gorilla/handlers@v1.5.1/cors.go:54 +0x610
github.com/openziti/fabric/controller/api.(*timeoutHandler).ServeHTTP.func1()
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/fabric@v0.17.135/controller/api/timeouts.go:79 +0xb4
created by github.com/openziti/fabric/controller/api.(*timeoutHandler).ServeHTTP
	/Users/curt/Repos/nf/github/pkg/mod/github.com/openziti/fabric@v0.17.135/controller/api/timeouts.go:72 +0x304
```

**Comment by ekoby** [comment]
check if it's still an issue
