### ISSUE TITLE
ziti router never exits if it can't connect to the controller

### ISSUE THREAD

**Issue by dovholuknf** [openziti/ziti#1755]
I tried to run a router today but messed up the controller address. The router would start but when pressing ctrl-c, it would never exit.

You do see this message:
```
[   5.024]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
```

And you see the router indicate it's exiting:
```[   8.287]   ERROR ziti/router/xgress_edge.(*Acceptor).Run: error accepting (closed)
[   8.287] WARNING ziti/router/xgress_edge.(*Acceptor).Run: exiting
[  10.086]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  15.142]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  20.312]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  25.534]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  30.791]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  36.100]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  41.420]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  46.971]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)] endpoint=[tls:3.134.108.210:8440]} unable to connect controller
[  53.564]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  60.251]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  68.980]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[  79.997]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)] endpoint=[tls:3.134.108.210:8440]} unable to connect controller
[  92.228]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:3.134.108.210:8440] error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)]} unable to connect controller
[ 109.175]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)] endpoint=[tls:3.134.108.210:8440]} unable to connect controller
[ 128.860]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {error=[error connecting ctrl (dial tcp 3.134.108.210:8440: i/o timeout)] endpoint=[tls:3.134.108.210:8440]} unable to connect controller
```

it just never seems to __actually__ stop. I admit i didn't actually way 'forever' but 128 seconds seems like enough  time to wait

**Comment by plorenz** [comment]
The default is 30 seconds, but it's configurable under

```
ctrl:
    startupTimeout: 5h
```
I tested, and mine shutdown after 30s. Do you have startupTimeout set to something larger?

**Comment by dovholuknf** [comment]
30s seems like an __eternity__ when I'm trying to shut something down... If the router connects, it shuts down immediately (like I'd want it to), it's only when the router can't connect to the controller at all that it seems to loop forever

the router config has no timeout set:
```
ctrl:
  endpoint:             tls:85.10.10.101:8440
```

Steps to reproduce:
start the controller
```
export ZITI_HOME=/opt/openziti
mkdir -p $ZITI_HOME

export ZITI_PWD=admin

export EXTERNAL_IP="85.10.10.100"
export ZITI_CTRL_EDGE_IP_OVERRIDE="${EXTERNAL_IP}"
export ZITI_CTRL_EDGE_ADVERTISED_ADDRESS="${EXTERNAL_DNS:-${EXTERNAL_IP}}"
export ZITI_CTRL_ADVERTISED_PORT=8440
export ZITI_CTRL_EDGE_ADVERTISED_PORT=8441

export ZITI_ROUTER_IP_OVERRIDE="${EXTERNAL_IP}"
export ZITI_ROUTER_ADVERTISED_ADDRESS="${EXTERNAL_DNS:-${EXTERNAL_IP}}"
export ZITI_ROUTER_PORT=8442

source /dev/stdin <<< "$(curl -sSL https://get.openziti.io/ziti-cli-functions.sh)"; expressInstall

ziti controller run $ZITI_HOME/$(hostname).yaml
```

start the router - the key is the router's controller config is totally wrong and never connects:
```
export CTRL_IP="85.10.10.100"
export ZITI_CTRL_EDGE_ADVERTISED_PORT=8441
ziti edge login $CTRL_IP:$ZITI_CTRL_EDGE_ADVERTISED_PORT -u admin -p admin -y
ziti edge create edge-router $router_name -o $ZITI_HOME/$router_name.jwt
ziti create config router edge --routerName ${router_name} --tunnelerMode none --output $ZITI_HOME/${router_name}.yml

export ZITI_HOME=/opt/openziti
mkdir -p $ZITI_HOME

export ZITI_PWD=admin

## here's the key - change the ip or whatever
export CTRL_IP="85.10.10.101"
export ZITI_CTRL_ADVERTISED_ADDRESS="${CTRL_IP}"
export ZITI_CTRL_ADVERTISED_PORT=8440
export ZITI_CTRL_EDGE_ADVERTISED_ADDRESS="${CTRL_IP}"
export ZITI_CTRL_EDGE_ADVERTISED_PORT=8441

router_name=r1
export EXTERNAL_IP="85.10.10.50"
export ZITI_ROUTER_IP_OVERRIDE="${EXTERNAL_IP}"
export ZITI_ROUTER_ADVERTISED_ADDRESS="${EXTERNAL_DNS:-${EXTERNAL_IP}}"
export ZITI_ROUTER_PORT=8410
export ZITI_ROUTER_LISTENER_BIND_PORT=8411


ziti router enroll $ZITI_HOME/${router_name}.yml --jwt $ZITI_HOME/${router_name}.jwt
ziti router run $ZITI_HOME/${router_name}.yml
```

**Comment by dovholuknf** [comment]
and if you don't use `--tunnelerMode none`, the router will stop but panics:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x316a3f6]

goroutine 38 [running]:
github.com/openziti/ziti/router/xgress_edge_tunnel.(*tunneler).Close(0xc00098e420?)
        github.com/openziti/ziti/router/xgress_edge_tunnel/tunneler.go:152 +0x16
github.com/openziti/ziti/router.(*Router).Shutdown(0xc000090e38?)
        github.com/openziti/ziti/router/router.go:294 +0x323
github.com/openziti/ziti/ziti/router.waitForShutdown(0xc000bbe440?)
        github.com/openziti/ziti/ziti/router/run.go:146 +0x265
created by github.com/openziti/ziti/ziti/router.run in goroutine 1
        github.com/openziti/ziti/ziti/router/run.go:117 +0x1188
```

**Comment by qrkourier** [comment]
I see something different with the router catches a TERM (15) signal, but it still doesn't exit. I can send it to the background with ctrl-z then `kill -KILL %1` as a workaround.

```
^C[   1.717]    INFO ziti/ziti/router.waitForShutdown: shutting down ziti-router
[   1.717]    INFO ziti/router/link.(*linkRegistryImpl).Shutdown: {linkCount=[0]} shutdown links in link registry
[   1.717] WARNING ziti/router/forwarder.(*Scanner).run: exited
[   1.717]   ERROR agent.(*handler).listen: {error=[accept unix /tmp/gops-agent.2498006.sock: use of closed network connection]} error accepting gops connection, closing gops listener
[   1.717]   ERROR agent.(*handler).listen.func1: {error=[close unix /tmp/gops-agent.2498006.sock: use of closed network connection]} error closing gops listener
[   1.717]   ERROR ziti/router/forwarder.(*Faulter).run: exited
[   1.717]   ERROR ziti/router/xgress_edge.(*Acceptor).Run: error accepting (closed)
[   1.717] WARNING ziti/router/xgress_edge.(*Acceptor).Run: exiting
[   1.717]    INFO transport/v2/tls.(*sharedListener).runAccept [tls:0.0.0.0:3023]: {error=[accept tcp [::]:3023: use of closed network connection]} listener closed, exiting
[   1.718]    INFO transport/v2/tls.(*sharedListener).runAccept [tls:0.0.0.0:3023]: exited
[   2.021]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:ziti.example.com:6262] error=[error connecting ctrl (remote error: tls: internal error)]} unable to connect controller
[   2.753]   ERROR ziti/router/env.(*networkControllers).connectToControllerWithBackoff.func2: {endpoint=[tls:ziti.example.com:6262] error=[error connecting ctrl (remote error: tls: internal error)]} unable to connect controller
```

**Comment by dovholuknf** [comment]
That seems similar to what I saw. from my logs i also show that it noticed/reacted but never actually quits. I had to kill -9 it. 
```
[   8.287] WARNING ziti/router/xgress_edge.(*Acceptor).Run: exiting
```

**Comment by smilindave26** [comment]
Closing per Clint's guidance
