### ISSUE TITLE
Controller panics on 'ziti agent cluster list'

### ISSUE THREAD

**Issue by karlpokus** [openziti/ziti#2055]
To reproduce:

- Run the docker tutorial https://openziti.io/docs/learn/quickstarts/network/local-with-docker and `docker exec` into the controller container
-  run `ziti agent cluster list`

The controller panics:

````
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x254a6c5]

goroutine 188 [running]:
github.com/openziti/channel/v2.(*channelImpl).rxer.func1()
	github.com/openziti/channel/v2@v2.0.128/impl.go:308 +0x3f
panic({0x35b5c40?, 0x5991310?})
	runtime/panic.go:770 +0x132
github.com/openziti/ziti/controller/raft.(*Controller).GetRaft(...)
	github.com/openziti/ziti/controller/raft/raft.go:244
github.com/openziti/ziti/controller/raft.(*Controller).ListMembers(0x0)
	github.com/openziti/ziti/controller/raft/member.go:40 +0x25
github.com/openziti/ziti/controller.(*Controller).agentOpRaftList(0x97efdf6400000003?, 0xc0025e1c50, {0x4196440, 0xc000e71b00})
	github.com/openziti/ziti/controller/agent.go:80 +0x3e
github.com/openziti/channel/v2.ReceiveHandlerF.HandleReceive(0x3589980?, 0xc00200cc00?, {0x4196440?, 0xc000e71b00?})
	github.com/openziti/channel/v2@v2.0.128/handler.go:99 +0x29
github.com/openziti/channel/v2.(*channelImpl).rxer(0xc003480f50?)
	github.com/openziti/channel/v2@v2.0.128/impl.go:359 +0x558
created by github.com/openziti/channel/v2.(*channelImpl).startMultiplex in goroutine 73
	github.com/openziti/channel/v2@v2.0.128/impl.go:288 +0xb8
````

**Comment by dovholuknf** [comment]
This is also reproducible by running `ziti edge quickstart` and trying to use `ziti agent cluster list` on that controller.
